# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('view_num', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf')),
                ('like_num', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6b63\u6587')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='\u662f\u5426\u88ab\u63a8\u8350')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u7c7b\u522b\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user', models.CharField(max_length=20, verbose_name='\u8bc4\u8bba\u4eba')),
                ('content', models.CharField(max_length=140, verbose_name='\u5185\u5bb9')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Blog', verbose_name='\u535a\u5ba2')),
            ],
        ),
        migrations.CreateModel(
            name='LikeBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(auto_now_add=True, verbose_name='\u70b9\u8d5e\u65f6\u95f4')),
                ('like_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Blog', verbose_name='\u535a\u5ba2')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u70b9\u8d5e\u4eba')),
            ],
            options={
                'verbose_name': '\u70b9\u8d5e',
                'verbose_name_plural': '\u70b9\u8d5e',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=16, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='article.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
