# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 14:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeblog',
            name='like_blog',
        ),
        migrations.RemoveField(
            model_name='likeblog',
            name='like_user',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_time'], 'verbose_name': '\u535a\u5ba2\u6587\u7ae0', 'verbose_name_plural': '\u535a\u5ba2\u6587\u7ae0'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['rank', '-create_time'], 'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time'], 'verbose_name': '\u8bc4\u8bba', 'verbose_name_plural': '\u8bc4\u8bba'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u6807\u7b7e', 'verbose_name_plural': '\u6807\u7b7e'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570'),
        ),
        migrations.AddField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 11, 14, 3, 8, 374000, tzinfo=utc), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.CharField(default=datetime.datetime(2016, 9, 11, 14, 3, 19, 954000, tzinfo=utc), max_length=200, verbose_name='\u56fe\u7247'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(default=datetime.datetime(2016, 9, 11, 14, 4, 12, 504000, tzinfo=utc), verbose_name='\u6458\u8981'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 11, 14, 4, 22, 680000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='\u4e0a\u7ea7\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Comment', verbose_name='\u5f15\u7528'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=140, verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
        migrations.DeleteModel(
            name='LikeBlog',
        ),
    ]
